# Generated by Django 2.2.2 on 2021-07-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students')),
                ('body', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('ONE', 'one'), ('TOW', 'tow'), ('THREE', 'three'), ('FOUR', 'four'), ('FIVE', 'five')], max_length=5)),
            ],
        ),
    ]
