# Generated by Django 2.2.2 on 2021-07-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comments')),
                ('body', models.TextField(blank=True, max_length=700, null=True)),
                ('starts', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('job', models.CharField(max_length=25)),
            ],
        ),
    ]
