# Generated by Django 2.2.2 on 2021-07-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('intro', models.TextField(blank=True, max_length=1000, null=True)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about')),
                ('link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ONE', 'one'), ('TOW', 'tow'), ('THREE', 'three'), ('NON', 'non')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/team')),
                ('face', models.URLField(blank=True, null=True)),
                ('inst', models.URLField(blank=True, null=True)),
                ('tele', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('hint', models.TextField(blank=True, max_length=700, null=True)),
                ('benifit', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/why')),
            ],
        ),
    ]
